Null terminate string copy in _dwarf_strtab_add
Reported by GCC in the Debian Cirrus-CI task:

libdwarf_str.c: In function '_dwarf_strtab_add':
libdwarf_str.c:55:2: error: 'strncpy' output truncated before terminating
nul copying as many bytes from a string as its length

  strncpy(&dbg->dbg_strtab[dbg->dbg_strtab_size], string, len - 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

libdwarf_str.c:41:8: note: length computed here
  len = strlen(string) + 1;
        ^~~~~~~~~~~~~~

len is calculated to include the NUL terminator at the end of the input
string, so the output will be terminated.